h = next(w['handle'] for w in rdp_windows() if w['class'] == 'TscShellContainerClass')
focus(h)
left,top,_,_ = win32gui.GetWindowRect(h)
win32api.SetCursorPos((left+886,top+914))
win32api.mouse_event(win32con.MOUSEEVENTF_LEFTDOWN,0,0,0,0)
win32api.mouse_event(win32con.MOUSEEVENTF_LEFTUP,0,0,0,0)
time.sleep(.8)
paste("Get-Process Everything | Where-Object MainWindowHandle -ne 0 | ForEach-Object { [LabWindow]::ShowWindow($_.MainWindowHandle,9); [LabWindow]::MoveWindow($_.MainWindowHandle,20,90,700,600,$true) }; Get-Process WizTree64 | Where-Object MainWindowHandle -ne 0 | ForEach-Object { [LabWindow]::MoveWindow($_.MainWindowHandle,270,270,1150,540,$true) }; [LabWindow]::ShowWindow([LabWindow]::GetConsoleWindow(),6)")
keys('{ENTER}')
time.sleep(4)
screenshot(h, 'C:/Users/Xxthe/Parallel_lab/.lab_work/rdp.png')
