h=next(w['handle'] for w in rdp_windows() if w['class']=='TscShellContainerClass')
focus(h)
left,top,_,_=win32gui.GetWindowRect(h)
win32api.SetCursorPos((left+930,top+914))
win32api.mouse_event(win32con.MOUSEEVENTF_LEFTDOWN,0,0,0,0)
win32api.mouse_event(win32con.MOUSEEVENTF_LEFTUP,0,0,0,0)
time.sleep(1)
keys('{F5}')
time.sleep(2)
screenshot(h,'C:/Users/Xxthe/OneDrive/Desktop/Cloud_Lab/Lab3/work/evidence/remote/11_instance_b_file.png')
win32api.keybd_event(win32con.VK_LWIN,0,0,0)
win32api.keybd_event(ord('D'),0,0,0)
time.sleep(.15)
win32api.keybd_event(ord('D'),0,win32con.KEYEVENTF_KEYUP,0)
win32api.keybd_event(win32con.VK_LWIN,0,win32con.KEYEVENTF_KEYUP,0)
time.sleep(1)
screenshot(h,'C:/Users/Xxthe/OneDrive/Desktop/Cloud_Lab/Lab3/work/evidence/remote/06_instance_b_software.png')
