state=json.loads((WORK/'state.json').read_text())
page.bring_to_front()
f=page.frame(name='compute-react-frame')
assert 'No AMIs in this Region' in f.locator('body').inner_text()
page.screenshot(path=str(WORK/'evidence/aws/cleanup_amis.png'))
state.setdefault('cleanup',{})['amis_absent']=True
(WORK/'state.json').write_text(json.dumps(state,indent=2))
page.goto('https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#Volumes:')
page.locator('#storage-react-frame').wait_for(state='attached')
f=page.frame(name='storage-react-frame')
f.get_by_role('button',name='Refresh volumes',exact=True).wait_for()
f.get_by_role('button',name='Refresh volumes',exact=True).click()
page.wait_for_timeout(1200)
print(f.locator('body').aria_snapshot())
