h=next(w['handle'] for w in rdp_windows() if w['class']=='TscShellContainerClass')
focus(h)
left,top,_,_=win32gui.GetWindowRect(h)
win32api.SetCursorPos((left+930,top+914))
win32api.mouse_event(win32con.MOUSEEVENTF_LEFTDOWN,0,0,0,0)
win32api.mouse_event(win32con.MOUSEEVENTF_LEFTUP,0,0,0,0)
time.sleep(.8)
paste(Path('C:/Users/Xxthe/Parallel_lab/.lab_work/copy_timestamp.txt').read_text())
keys('{ENTER}')
time.sleep(4)
screenshot(h,'C:/Users/Xxthe/Parallel_lab/.lab_work/rdp.png')
