state=json.loads((WORK/'state.json').read_text())
page.bring_to_front()
page.goto('https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#Images:visibility=owned-by-me')
page.locator('#compute-react-frame').wait_for(state='attached')
f=page.frame(name='compute-react-frame')
f.get_by_role('button',name='Refresh AMIs',exact=True).wait_for()
f.get_by_role('button',name='Refresh AMIs',exact=True).click()
page.wait_for_timeout(1000)
for box in f.get_by_role('checkbox').all():
 if box.is_checked(): box.click()
for im in state['images'].values():
 box=f.get_by_role('checkbox',name='Select image: '+im['id'],exact=True)
 if not box.is_checked(): box.click()
checked=f.get_by_role('checkbox').evaluate_all('(els)=>els.filter(e=>e.checked).map(e=>e.getAttribute("aria-label"))')
print('Selected',checked)
assert all(i is None or i.startswith('Select image: ') or 'all' in i.lower() for i in checked)
f.get_by_role('button',name='Actions',exact=True).first.click()
f.get_by_role('menuitem',name='Deregister AMI',exact=True).last.click()
print(f.get_by_role('dialog').aria_snapshot())
