import re
state=json.loads((WORK/'state.json').read_text())
instance=state['instances']['C']
page.bring_to_front()
page.goto('https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#InstanceDetails:instanceId='+instance['id'])
page.locator('#compute-react-frame').wait_for(state='attached')
f=page.frame(name='compute-react-frame')
f.get_by_role('heading',name='Instance summary for '+instance['id']+' (Instance-C-Hamdan)',exact=True).wait_for()
f.get_by_text('Running',exact=True).first.wait_for(timeout=25000)
body=f.locator('body').inner_text()
for field,label in [('public_ip','Public IPv4 address'),('public_dns','Public DNS'),('private_ip','Private IPv4 addresses')]:
 instance[field]=re.search(label+r'\n([^\s|]+)',body).group(1)
instance['state']='running'
page.screenshot(path=str(WORK/'evidence/aws/14_instance_c_running.png'))
f.get_by_role('tab',name='Networking',exact=True).click()
page.wait_for_timeout(800)
body=f.get_by_role('tabpanel',name='Networking',exact=True).inner_text()
instance['az']=re.search(r'Availability zone\n([^\s]+)',body).group(1)
instance['subnet']=re.search(r'subnet-[a-f0-9]+',body).group(0)
f.get_by_role('tab',name='Storage',exact=True).click()
page.wait_for_timeout(800)
body=f.get_by_role('tabpanel',name='Storage',exact=True).inner_text()
instance['volumes']=list(dict.fromkeys(re.findall(r'vol-[a-f0-9]+',body)))
(WORK/'state.json').write_text(json.dumps(state,indent=2))
print(json.dumps(instance,indent=2))
print('STORAGE',body)
f.get_by_role('button',name='Actions',exact=True).first.click()
f.get_by_role('menuitem',name='Monitor and troubleshoot',exact=True).click()
f.get_by_role('menuitem',name='Get system log',exact=True).click()
