command = Path(sys.argv[2]).read_text(encoding='utf-8').strip()
h = next(w['handle'] for w in rdp_windows() if w['class'] == 'TscShellContainerClass')
focus(h)
win32gui.SetWindowPos(h, 0, 20, 30, 1458, 947, win32con.SWP_NOZORDER)
left,top,_,_ = win32gui.GetWindowRect(h)
win32api.SetCursorPos((left+650,top+137))
win32api.mouse_event(win32con.MOUSEEVENTF_LEFTDOWN,0,0,0,0)
win32api.mouse_event(win32con.MOUSEEVENTF_LEFTUP,0,0,0,0)
time.sleep(.3)
win32api.keybd_event(win32con.VK_LWIN,0,0,0)
win32api.keybd_event(ord('R'),0,0,0)
time.sleep(.15)
win32api.keybd_event(ord('R'),0,win32con.KEYEVENTF_KEYUP,0)
win32api.keybd_event(win32con.VK_LWIN,0,win32con.KEYEVENTF_KEYUP,0)
time.sleep(.7)
paste(command)
keys('{ENTER}')
time.sleep(3)
screenshot(h, 'C:/Users/Xxthe/Parallel_lab/.lab_work/rdp.png')
