state=json.loads((WORK/'state.json').read_text())
page=next(p for p in context.pages if state['instances']['B']['id'] in p.url)
page.bring_to_front()
page.goto('https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#InstanceDetails:instanceId='+state['instances']['B']['id'])
page.locator('#compute-react-frame').wait_for(state='attached')
f=page.frame(name='compute-react-frame')
f.get_by_role('heading',name='Instance summary for i-0697cd44b881f1b12 (Instance-B-Hamdan)',exact=True).wait_for()
page.wait_for_timeout(1000)
f.get_by_role('button',name='Instance state',exact=True).first.click()
f.get_by_role('menuitem',name='Stop instance',exact=True).click()
d=f.get_by_role('dialog')
assert state['instances']['B']['id'] in d.inner_text()
d.get_by_role('button',name='Stop',exact=True).click()
print('Graceful stop requested for Instance-B.')
